---
- name:  Install and start Apache
  hosts:  all
  gather_facts:  False
  tasks:
  - name:  install apache
    yum:
      name:  httpd
      state:  present
  
  - name:  start httpd service 
    service:
      name:  httpd
      state: started
